# Override file for local development
# This file is automatically loaded with docker-compose up
# Create this file to override default settings

version: '3.8'

services:
  backend:
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      NODE_ENV: development
      JWT_SECRET: development-jwt-secret-not-for-production
    
  postgres:
    volumes:
      - ./backups:/backups
    ports:
      - "5432:5432"